cp exodia-mirrorlist /etc/pacman.d/
cp alhp-mirrorlist /etc/pacman.d/
cp archcraft-mirrorlist /etc/pacman.d/
cp arcolinux-mirrorlist /etc/pacman.d/
cp axyl-mirrorlist /etc/pacman.d/
cp chaotic-mirrorlist /etc/pacman.d/
cp endeavouros-mirrorlist /etc/pacman.d/
cp reborn-mirrorlist /etc/pacman.d/
cp ../pacman.conf /etc/